version: 2.1

jobs:
  build:
    docker:
    - image: actionml/harness-sdk:latest
      entrypoint: /entrypoint.sh
    environment:
    - SDK_VERBOSE: true
    - JVM_OPTS: -Xms512m -Xmx3584m -Xss2m
    steps:
    - checkout
    - run:
        name: Build environment details
        command: /details.sh
    - run:
        name: Build harness-cli dist
        command: make dist
    - persist_to_workspace:
        root: /root/project/dist
        paths:
        - ./
  publish:
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: /root/project/dist
    - run:
        name: Docker login
        command: |
          echo -n ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    - run:
        name: Build harness-cli docker image
        command: |
          SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
          DATE_BUILD=$(date +'%Y-%m-%d')
          case "${CIRCLE_BRANCH}" in
            "master")
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=$SHORT_GIT_HASH --build-arg DATE_BUILD=$DATE_BUILD --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/harness-cli:latest ./
            ;;
            "develop")
              echo $CIRCLE_BRANCH
              echo $CIRCLE_TAG
              # creates a short hash but cant figure out how to get into the tags below $(echo $CIRCLE_SHA1 | cut -c -7)
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=$SHORT_GIT_HASH --build-arg DATE_BUILD=$DATE_BUILD --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/harness-cli:${CIRCLE_BRANCH} ./
            ;;
            "devops")
              echo $CIRCLE_BRANCH
              echo $CIRCLE_TAG
              echo $DATE_BUILD
              echo $SHORT_GIT_HASH
              # creates a short hash but cant figure out how to get into the tags below $(echo $CIRCLE_SHA1 | cut -c -7)
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=$SHORT_GIT_HASH --build-arg DATE_BUILD=$DATE_BUILD --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/harness-cli:${CIRCLE_BRANCH} ./
            ;;
            "ci")
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=$SHORT_GIT_HASH --build-arg DATE_BUILD=$DATE_BUILD --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/harness-cli:${CIRCLE_BRANCH} ./
            ;;
            *)
            ;;
          esac
    - run:
        name: Publish docker image
        command: |
          SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
          DATE_BUILD=$(date +'%Y-%m-%d')
          
          case "${CIRCLE_BRANCH}" in
            "master")
              docker image push actionml/harness-cli:latest
            ;;
            "develop")
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}
              
              docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              
              docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
            ;;
            "devops")
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}
              
              docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              
              docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
              
            ;;
            "ci")
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}
              
              docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              
              docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
            ;;
            *)
            ;;
          esac
  test:
    docker:
    - image: alpine
    steps:
    - run: echo "unit or other tests"

workflows:
  version: 2
  default:
    jobs:
    - build
    - test
    - publish:
        requires:
        - build
        - test
