version: 2.1

jobs:
  build:
    docker:
    - image: actionml/harness-sdk:latest
      entrypoint: /entrypoint.sh
    environment:
    - SDK_VERBOSE: true
    - JVM_OPTS: -Xms512m -Xmx3584m -Xss2m
    steps:
    - checkout
    #- restore_cache:
    #     keys:
    #     - rest-api-{{ checksum "rest-server/build.sbt" }}
    - run:
        name: Build environment details
        command: /details.sh
    - run:
        name: Build harness-cli dist
        command: make dist
    #- save_cache:
    #    key: rest-api-{{ checksum "rest-server/build.sbt" }}
    #    paths:
    #    - /root/.sbt
    #    - /root/.ivy2
    - persist_to_workspace:
        root: /root/project/dist
        paths:
        - ./
  publish:
    docker:
    - image: docker:stable
    # environment:
    # - SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    # - DATE_BUILD: $(date +'%d-%m-%Y')

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: /root/project/dist
    - run:
        name: Docker login
        command: |
          echo -n ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    - run:
        name: Export var
        command: |
          export SHORT_GIT_HASH=$(echo ${CIRCLE_SHA1} | cut -c -7)
          export DATE_BUILD=$(date +'%d-%m-%Y')
          echo "HASH - $SHORT_GIT_HASH"
          echo "Date - $DATE_BUILD"
    - run:
        name: Build harness-cli docker image
        command: |
          case "${CIRCLE_BRANCH}" in
            "master")
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=${SHORT_GIT_HASH} --build-arg DATE_BUILD=${DATE_BUILD} -t actionml/harness-cli:latest ./
            ;;
            "develop")
              echo $CIRCLE_BRANCH
              echo $CIRCLE_TAG
              # creates a short hash but cant figure out how to get into the tags below $(echo $CIRCLE_SHA1 | cut -c -7)
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=${SHORT_GIT_HASH} --build-arg DATE_BUILD=${DATE_BUILD} -t actionml/harness-cli:${CIRCLE_BRANCH} ./
            ;;
            "devops")
              echo $CIRCLE_BRANCH
              echo $CIRCLE_TAG
              echo $SHORT_GIT_HASH
              # creates a short hash but cant figure out how to get into the tags below $(echo $CIRCLE_SHA1 | cut -c -7)
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=${SHORT_GIT_HASH} --build-arg DATE_BUILD=${DATE_BUILD} -t actionml/harness-cli:${CIRCLE_BRANCH} ./
            ;;
            "ci")
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=${SHORT_GIT_HASH} --build-arg DATE_BUILD=${DATE_BUILD} -t actionml/harness-cli:${CIRCLE_BRANCH} ./
            ;;
            *)
            ;;
          esac
    - run:
        name: Publish docker image
        command: |
          case "${CIRCLE_BRANCH}" in
            "master")
              docker image push actionml/harness-cli:latest
            ;;
            "develop")
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}
            ;;
            "devops")
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}
              docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${CIRCLE_SHA1}
              docker image push actionml/harness-cli:${CIRCLE_SHA1}
              # docker tag actionml/harness-cli:${CIRCLE_BRANCH} actionml/harness-cli:${DATE_BUILD}
              # docker image push actionml/harness-cli:${DATE_BUILD}
              
            ;;
            "ci")
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}
            ;;
            *)
            ;;
          esac
  test:
    docker:
    - image: alpine
    steps:
    - run: echo "unit or other tests"

workflows:
  version: 2
  default:
    jobs:
    - build
    - test
    - publish:
        requires:
        - build
        - test
