version: 2.1

jobs:
  build:
    docker:
    - image: actionml/harness-sdk:latest
      entrypoint: /entrypoint.sh
    environment:
    - SDK_VERBOSE: true
    - JVM_OPTS: -Xms512m -Xmx3584m -Xss2m
    steps:
    - checkout
    - run:
        name: Build environment details
        command: /details.sh
    - run:
        name: Build harness-cli dist
        command: make dist
    - persist_to_workspace:
        root: /root/project/dist
        paths:
        - ./
  publish:
    docker:
    - image: docker:stable
    environment:
      SHELL_ENV: /etc/profile
    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: /root/project/dist
    - run:
        name: Docker login
        command: |
          echo -n ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    - run:
        name: Build harness-cli docker image
        command: |
          echo 'export SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $SHELL_ENV
          echo 'export DATE_BUILD=$(date +'%Y-%m-%d')' >> $SHELL_ENV
          source $SHELL_ENV
          
          echo "SHORT_GIT_HASH $SHORT_GIT_HASH"
          echo "DATE_BUILD $DATE_BUILD"
          
          case "${CIRCLE_BRANCH}" in
            master|develop|devops)
              docker image build -f Dockerfile --build-arg version=ci --build-arg GIT_HASH=$SHORT_GIT_HASH --build-arg DATE_BUILD=$DATE_BUILD --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/harness-cli:latest ./
            ;;
            *)
            ;;
          esac
    - run:
        name: Publish docker image
        command: |
          source $SHELL_ENV
          
          case "${CIRCLE_BRANCH}" in
            "master")
              docker image push actionml/harness-cli:latest
            ;;
            develop|devops)
              docker tag actionml/harness-cli:latest actionml/harness-cli:${CIRCLE_BRANCH}
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}
              
              docker tag actionml/harness-cli:latest actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$SHORT_GIT_HASH
              
              docker tag actionml/harness-cli:latest actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
              docker image push actionml/harness-cli:${CIRCLE_BRANCH}-$DATE_BUILD
            ;;
            *)
            ;;
          esac
  test:
    docker:
    - image: alpine
    steps:
    - run: echo "unit or other tests"

workflows:
  version: 2
  default:
    jobs:
    - build
    - test
    - publish:
        requires:
        - build
        - test
