#!/usr/bin/env bash

. "$(cd "`dirname "$0"`"; pwd)/common-functions.sh"

RESOURCE_TYPE=$1
RESOURCE_ID=$2
line="=================================================================="

if [ -z "${RESOURCE_TYPE}" ] || [ "${RESOURCE_TYPE}" = "engines" ] || [ "${RESOURCE_TYPE}" = "users" ] ; then
  echo -e "${CYAN}Harness CLI settings${NC}"
  echo -e "${CYAN}${line}"
  status_line "HARNESS_CLI_HOME" "${HARNESS_CLI_HOME}"
  status_line "HARNESS_CLI_SSL_ENABLED" "${HARNESS_CLI_SSL_ENABLED}"
  status_line "HARNESS_CLI_AUTH_ENABLED" "${HARNESS_CLI_AUTH_ENABLED}"
  status_line "HARNESS_SERVER_ADDRESS" "${HARNESS_SERVER_ADDRESS}"
  status_line "HARNESS_SERVER_PORT" "${HARNESS_SERVER_PORT}"
  echo -e "${line}${NC}"

  # output status
  color="${GREEN}"; status="OK"
  harness_running || { color="${RED}"; status="FAILED"; }
  echo -e "${color}Harness Server status: ${status}${NC}"

  harness_running || exit $?

  ## engines
  #
  if [ "${RESOURCE_TYPE}" = "engines" ]; then
    if [ -z ${RESOURCE_ID} ]; then
      "${HARNESS_CLI_HOME}"/engines.py status --all_engines ${USER_ARGS} || exit $?
    else
      "${HARNESS_CLI_HOME}"/engines.py status -e "${RESOURCE_ID}" ${USER_ARGS} || exit $?
    fi
  fi

  ## users
  #
  if [ "${RESOURCE_TYPE}" = "users" ]; then
    if [ -z "${RESOURCE_ID}" ]; then
      "${HARNESS_CLI_HOME}"/users.py status --all_users ${USER_ARGS} || exit $?
    else
      "${HARNESS_CLI_HOME}"/users.py status --user_id "${RESOURCE_ID}" ${USER_ARGS} || exit $?
    fi
  fi

else # bad type.
  echo -e "${RED}Bad resource type for status: ${RESOURCE_TYPE}${NC}"
  exit 1
fi



