#!/usr/bin/env bash

. "$(cd "`dirname "$0"`"; pwd)/common.sh"

echo
echo -e "${CYAN}Harness CLI Help${NC}"
echo -e "${CYAN}Harness must be running and the address defined for these to work.${NC}"
echo -e "${CYAN}Configure the CLI in ${HARNESS_CLI_HOME}/harness-cli-env${NC}"
echo

echo -e "   ${CYAN}harness-cli add </path/to/engine-config.json>${NC}"
echo -e "       Create a new engine instance and set it's configuration"
echo ""

echo -e "   ${CYAN}harness-cli update <engine-config.json>${NC}"
echo -e "       Resets the Engine instance parameters."
echo ""

echo -e "   ${CYAN}harness-cli import <engine-id> <path/to/events/json/files> ${NC}"
echo -e "       Imports events into the engine specified. The path can be to a directory or a single file."
echo ""

echo -e "   ${CYAN}harness-cli delete <engine-id>${NC}"
echo -e "       Deletes engine and all data"
echo ""

echo -e "   ${CYAN}harness-cli train <engine-id>${NC}"
echo -e "       For batch trained Engines this creates a model from previously accumulated data."
echo ""

echo -e "   ${CYAN}harness-cli status [[ engines | engines <engine-id>]]${NC}"
echo -e "       Prints a status message for the harness server, all engines, or the engine specified."
echo ""

echo -e "   ${CYAN}harness-cli user-add [client <engine-id> | admin]${NC}"
echo -e "       Returns a new user-id their secret. Grants the role's permissions."
echo ""

echo -e "   ${CYAN}harness-cli user-delete <user-id>${NC}"
echo -e "       Returns the user-id for the deleted user and deletes all attached permissions."
echo -e "       Warning: not implemented yet."
echo ""

echo -e "   ${CYAN}harness-cli grant <user-id> [client <engine-id> | admin]${NC}"
echo -e "       Returns true if permissions are added to the user-id"
echo -e "       Warning: only one engine-id can be accessed by a \"client\" user currently."
echo ""

echo -e "   ${CYAN}harness-cli revoke <user-id> [client <engine-id>| admin]${NC}"
echo -e "       Revokes the user permissions for the engine specified, or removes admin permissions."
echo ""

echo -e "   ${CYAN}harness-cli status users [<user-id>]${NC}"
echo -e "       Prints the permissions for all users, or the user specified."
echo -e "       Warning: not implemented yet."
echo ""
